import type {Metadata} from "next";
import {createServerComponentClient} from '@supabase/auth-helpers-nextjs';
import {cookies} from 'next/headers';


import '@/app/globals.css';
import AuthProvider from "@/components/AuthProvider";
import React from "react";
import Sidebar from "@/app/chat/sideBar";


// do not cache this layout
export const revalidate = 0;

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const supabase = createServerComponentClient({cookies});

    const {
        data: {session},
    } = await supabase.auth.getSession();

    const {
        data: {user},
    } = await supabase.auth.getUser();


    // if user exits, then get more user details from profile table
    if (user) {
        const {data, error} = await supabase.from('profiles').select().eq('id', user.id).single();
        if (data) {
            user['profile'] = data;
        }
    }

    return (
        <div className="">
            <div className="">
                <AuthProvider
                    accessToken={session?.access_token}
                    user={user}
                >
                    <Sidebar/>
                    <div className="flex-1 bg-gray-100 overflow-auto" style={{paddingLeft: '20%'}}>
                        {children}
                    </div>
                </AuthProvider>
            </div>
        </div>
    );
}
