import type {Metadata} from "next";
import {Inter} from "next/font/google";
// import "./globals.css";
// import UserProvider from "@/app/context/username";
import {createServerComponentClient} from '@supabase/auth-helpers-nextjs';
import {cookies} from 'next/headers';


import '@/app/globals.css';
import AuthProvider from "@/components/AuthProvider";
import {redirect} from "next/navigation";

const inter = Inter({subsets: ["latin"]});

// do not cache this layout
export const revalidate = 0;

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const supabase = createServerComponentClient({cookies});

    const {
        data: {session},
    } = await supabase.auth.getSession();

    const {
        data: {user},
    } = await supabase.auth.getUser();


    return (
        <html lang="en">
        <body>
        <div className="">
            <main
                className="">
                <AuthProvider
                    accessToken={session?.access_token}
                    user={user}
                >
                    {children}
                </AuthProvider>
            </main>
        </div>
        </body>
        </html>
    );
}
